### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by ghost** [opeious/Pokemon3DStoUnity#11]
Hi hope you can help, I keep getting errors when I try to Import. I've split my binaries into Pokemon folders but haven't been able to actually start converting the binary files in Unity yet. I've attached the errors generated in console below (errors.txt), I'm sure I've just done something wrong on my end, any ideas?

[errors.txt](https://github.com/opeious/Pokemon3DStoUnity/files/6166471/errors.txt)

**Comment by opeious** [comment]
Could you share a bit more details on the folder structure and which folder option you are using?

So in the preview section you can see which binaries its trying to merge together, every Pokemon merged binary subsection should only be trying to merge binaries from one mon.

Correct:
![correct](https://user-images.githubusercontent.com/3764951/111682051-ede30380-8849-11eb-8443-b69403d0ecf5.png)

Incorrect, and might be the cause of this issue:
![maybeincorrect](https://user-images.githubusercontent.com/3764951/111682065-f1768a80-8849-11eb-986a-b98f24ad4e27.png)

**Comment by ghost** [comment]
Hey @opeious, I think the merged binaries look okay:
<img width="579" alt="binaries" src="https://user-images.githubusercontent.com/59779876/111684896-31744800-881f-11eb-9992-e8de45b6d925.png">

The github repo, Bin3DS and Exported folders are all in the root of Assets. I'm working in a stock URP project, using the default settings on the plug-in before import and getting the two errors in first post?

**Comment by opeious** [comment]
Just confirming the element 0 of each binary is the model's binary, apart from that the settings look fine to me, maybe something is wrong with the binaries. 
Which game are they from? I have only tested the binaries of Sun and Moon mainly.
Could you email them to me? or send me them on discord?
https://discord.gg/8yTPtmw5 (Server link)

**Comment by ghost** [comment]
Looks like my binaries were messed up, thanks a lot for your help @opeious
